### ISSUE TITLE
npm init modulo - launching to GH pages bug - fix .nojekyll

### ISSUE THREAD

**Issue by michaelpb** [modulojs/modulo#42]
There is a typo in the `.nojekyll` file in the starter project used by `create-modulo` - should not have dash

**Comment by nitin1chandani** [comment]
Their is no dash in .nojekyll file.

**Comment by michaelpb** [comment]
fixed in https://github.com/michaelpb/create-modulo/commit/81d3c69188c806b7c8c0dd05c396f3825b285932
